---
- hosts: automation
  remote_user: vagrant
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    LOGSTASH_VERSION: 7.8.1
  tasks:
    - name: Instalando Pacotes Necessarios
      apt:
        name: ["apt-transport-https","ca-certificates","curl","gnupg-agent","software-properties-common","python3","python3-pip","vim","openjdk-11-jre","wget","tree"]
        update_cache: yes
        state: present

    - name: Adicionando Chave do Docker
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Adicionando Repositorio do Docker
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release}} stable"
        state: present

    - name: Instalando Docker
      apt:
        name: docker-ce
        update_cache: yes
        state: present
      notify: docker-service

    - name: Validando Instalador do Logstash
      stat:
        path: "/root/logstash-{{ LOGSTASH_VERSION }}.deb"
      register: logstash_installer
    - name: Baixando Pacote do Logstash
      get_url:
        url: "https://artifacts.elastic.co/downloads/logstash/logstash-{{ LOGSTASH_VERSION }}.deb"
        dest: "/root/logstash-{{ LOGSTASH_VERSION }}.deb"
      when: not logstash_installer.stat.exists

    - name: Garantindo configuração do rsyslog.conf
      lineinfile:
        path: /etc/rsyslog.conf
        regexp: '^local7'
        line: "local7.*			/var/log/docker.log"
      notify: rsyslog-service

  handlers:
    - name: docker-service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: rsyslog-service
      systemd:
        name: rsyslog
        state: restarted
